version: "2"

volumes:
  postgres_volume:

networks:
  app:

services:
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data

  docker_test:
    build: .
    container_name: docker_test
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      TZ: Europe/Moscow
